version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polvebra_dev
      - MYSQL_USER=pol
      - MYSQL_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: 
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    depends_on: 
      - mysql
    volumes:
      - .:/app:rw,cached
    

  nginx:
    image: nginx:1.17.9-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./infra/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app



volumes:
  dbdata:
    driver: local


